name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload tarball via SFTP
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}  
        port: ${{ secrets.SSH_PORT }}
        source: ./* 
        target: ./

    - name: Deploy and Run Docker Container on On-Prem Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker compose -f ./compose/dev/docker-compose.yml down || true
          docker compose -f ./compose/dev/docker-compose.yml up --build -d